#!/bin/bash
#$ -cwd
#$ -l mem_free=10g
#$ -l num_proc=16
#$ -l h_rt=0:40:00
#$ -S /bin/bash
source activate bpr

set -u
set -e
set -x

code=/home/hltcoe/jweese/src/bprForBli/scale
vecname=vecs

src=$1
tgt=$2
dict=$3

topN=10

python "$code"/train_bilingual_embeddings.py \
  --english "$tgt" \
  --foreign "$src" \
  --dict "$dict" \
  --to_project "$tgt" \
  --gentestfile testset \
  --verbose \
  | paste -d' ' <(cut -d' ' -f1 "$tgt") - >"$vecname".tgt.txt
ln -sf "$src" "$vecname".src.txt

vecs=("$vecname".{src,tgt}.txt)
for v in "${vecs[@]}"; do
  TMPDIR=/scratch python -m pymagnitude.converter \
    -i "$v" -o "${v/%txt/magnitude}"
done

TMPDIR=/scratch python "$code"/get_neighbors.py \
  "${vecs[@]/%txt/magnitude}" -n "$topN" \
  < <(cut -f1 testset) >test.out
exec "$code"/accuracy.pl testset test.out >result
